### ISSUE TITLE
ResurrectionIcon In WoW:classic?

### ISSUE THREAD

**Issue by guppy42** [nebularg/PitBull4#10]
This was supposedly added a while back but I cannot for the life of me figure out where it's supposed to be enabled.

**Comment by nebularg** [comment]
The API for it doesn’t exist in Classic so the indicator was removed for that version. I believe there was a library for it in the past so it may be possible to bring it back.

**Comment by perks** [comment]
`UnitHasIncomingResurrection` is available to the classic client no?  As for summon `C_IncomingSummon.HasIncomingSummon` might not be since it's pretty new

**Comment by nebularg** [comment]
It exists yes, if someone can test if the event `INCOMING_RESURRECT_CHANGED` actually fires, that would be an easy fix

**Comment by perks** [comment]
According to https://github.com/Ketho/BlizzardInterfaceResources/blob/classic/Resources/Events.lua#L742 it should be

**Comment by nebularg** [comment]
live vs classic :p
