### ISSUE TITLE
Modules\PhaseIcon\PhaseIcon.lua:27: attempt to call global 'UnitInPhase' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [nebularg/PitBull4#13]
On Beta

Message: ...face\AddOns\PitBull4\Modules\PhaseIcon\PhaseIcon.lua:27: attempt to call global 'UnitInPhase' (a nil value)
Time: Thu Jul 30 12:01:44 2020
Count: 1
Stack: ...face\AddOns\PitBull4\Modules\PhaseIcon\PhaseIcon.lua:27: attempt to call global 'UnitInPhase' (a nil value)
[string "@Interface\AddOns\PitBull4\Modules\PhaseIcon\PhaseIcon.lua"]:27: in function `GetTexture'
[string "@Interface\AddOns\PitBull4\ModuleHandling\IndicatorModule.lua"]:35: in function <...e\AddOns\PitBull4\ModuleHandling\IndicatorModule.lua:25>
[string "@Interface\AddOns\PitBull4\ModuleHandling\IndicatorModule.lua"]:113: in function `UpdateFrame'
[string "@Interface\AddOns\PitBull4\ModuleHandling\Module.lua"]:313: in function `Update'
[string "@Interface\AddOns\PitBull4\UnitFrame.lua"]:796: in function `Update'
[string "@Interface\AddOns\PitBull4\UnitFrame.lua"]:637: in function `RecheckConfigMode'
[string "@Interface\AddOns\PitBull4\Options\ConfigMode.lua"]:59: in function `RecheckConfigMode'
[string "@Interface\AddOns\PitBull4\Main.lua"]:1587: in function `OnProfileChanged'
[string "@Interface\AddOns\PitBull4\Main.lua"]:1646: in function <Interface\AddOns\PitBull4\Main.lua:1616>
[string "=[C]"]: ?
[string "@Interface\AddOns\Carbonite\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...\AddOns\Carbonite\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Carbonite\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Carbonite\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:620: in function <...\AddOns\Carbonite\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:493: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:616: in function `TimeManager_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1353: in function <Interface\FrameXML\UIParent.lua:1250>

Locals: <none>

**Comment by nebularg** [comment]
Fixed in 2e82a09248a9395b802c3aa14abb87e47832e126
