### ISSUE TITLE
New DogTag error?

### ISSUE THREAD

**Issue by rakkarage** [nebularg/PitBull4#18]
`Message: invalid key to 'next'
Time: Sat Mar 20 14:46:42 2021
Count: 1
Stack: invalid key to 'next'
[string "=[C]"]: in function `(for generator)'
[string "@Interface\AddOns\PitBull4\Modules\DogTagTexts\Libs\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua"]:49: in function <...Texts\Libs\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua:46>
[string "@Interface\AddOns\PitBull4\Modules\DogTagTexts\Libs\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua"]:56: in function <...Texts\Libs\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua:55>

Locals: (*temporary) = <table> {
}
(*temporary) = "raid1target"`

i have been getting this error intermittently for the last week or so...
not even using dogtags? I added "Outline()" to one text?
i have removed all other addons and it still happens... 
i reset my pitbull profile and rebuilt from scratch and it still happens...
argh! any help would be appreciated.
i guess i will try enabling the pitbull dogtag module that is disabled by default idk

**Comment by nebularg** [comment]
[This](https://www.curseforge.com/wow/addons/libdogtag-unit-3-0/issues/32) seems to be a long standing issue in DogTags. I should probably split it off into it's own addon so when it's disabled, the lib isn't still doing stuff in the background

**Comment by nebularg** [comment]
0e870647cfd1fe18d4d3a7cb4bb48c6651936018 should fix this but just not loading dogtags.
