### ISSUE TITLE
Reduce ScriptEnv.Short threashold under 10000

### ISSUE THREAD

**Issue by MichelPate** [nebularg/PitBull4#19]
Hi,
I was wondering why the current `Short` function doesn't format values < 10000, like 1k6 for 1600. Specially since SL, health numbers are smaller. It would make my UI a bit more readable too. It is a request, not an issue at all, the addon is perfect !

**Comment by nebularg** [comment]
Added `Shorter` in https://github.com/nebularg/PitBull4/commit/5d3f30b7702fe2a5f2c93e2fc4ea90b438efca1f
