### ISSUE TITLE
Remove weapon buffs?

### ISSUE THREAD

**Issue by rakkarage** [nebularg/PitBull4#21]
when you hide the blizzard aura bar you lose the ability to cancel weapon auras?
you can cancel most buffs by right clicking them but not weapon buffs?

i tried cancelaura etc but not work

https://us.forums.blizzard.com/en/wow/t/shadowcore-oil-cancelaura-macro/916151/3

this thread details a solution to the problem

/click TempEnchant1

you can use this macro, but the macro does not work when the bar is hidden... so have to disable the disable blizzard buffs options to use the macro or click off the buff....

**is there is any reason removing weapon buffs like oils and sharpening stones does not work with the pitbull auras?**

when switching from dps to tank spec I wanna change oil from damage to heal

thanks a lot

**Comment by nebularg** [comment]
Can you not just apply the other oil and have it overwrite the current one?

Temporary enchants have a special API for cancelling them and it requires being called from a secure frame (which PB auras are not). Looks like `TempEnchant1` et al don't get an id set until they're shown at least once, so I could just do that to allow that macro to work.

As a stop gap, if you change the macro to

```
/run TempEnchant1:SetID(16)
/click TempEnchant1
```
that will remove it from your main hand

**Comment by rakkarage** [comment]
you sometimes can remove it by replacing it except when weighted or sharpening stone used cannot says "invalid target" error idk
thanks for the workaround, it works around!
