### ISSUE TITLE
TBC Rank heals - visual heal module update

### ISSUE THREAD

**Issue by Mcsofty** [nebularg/PitBull4#22]
I'm not great at knowing what has been flagged already, however rank 10 Holy  Light isn't working on current build, i have to down rank to see predicted heals.

I wasnt sure if this issue is specific to this spell or just the visual heals module needing updated in general, thanks for the addon ive been using pitbull since forever.

**Comment by nebularg** [comment]
It looks like I'm pulling from an outdated repo for the library used to show that, thanks for bringing that to me attention
