### ISSUE TITLE
LibHealComm-4.0-92.lua:2082: table index is nil

### ISSUE THREAD

**Issue by Jakobud** [nebularg/PitBull4#29]
I got this today. Never seen it happen before.

```
...\VisualHeal\Libs\LibHealComm-4.0\LibHealComm-4.0-92.lua:2082: table index is nil
[string "@PitBull4\Modules\VisualHeal\Libs\LibHealComm-4.0\LibHealComm-4.0-92.lua"]:2082: in function `?'
[string "@PitBull4\Modules\VisualHeal\Libs\LibHealComm-4.0\LibHealComm-4.0-92.lua"]:2707: in function <...\VisualHeal\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2705>

Locals:
InCombatSkipped
```

Maybe I should report this to the LibHealComm library but I dunno where the repo or issues are for that (like most Wowace libraries)

**Comment by Jakobud** [comment]
Also, this was on Burning Crusade Classic.

**Comment by nebularg** [comment]
or rather, I just pushed a new [alpha file](https://www.curseforge.com/wow/addons/pitbull-unit-frames-4-0/files/3482155)  using that version, let me know if that works

**Comment by nebularg** [comment]
Looks like it tries to get the spell id from the name if it can't get it from the aura, which can fail if the spell name isn't cached and it has to be fetched from the server first.

Anyway, I've tagged a release with the new lib so I'm going to close this.  If you get this error again you can try creating an issue on https://www.curseforge.com/wow/addons/libhealcomm-4-0
