### ISSUE TITLE
focus exception

### ISSUE THREAD

**Issue by absgbnb1** [nebularg/PitBull4#39]
Date: 2022-09-04 02:30:27
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\PitBull4\Main.lua line 1872:
   Bad unit set on Singleton Classification "foucs".  "focus" is not a singleton UnitID
Debug:
   [string "=[C]"]: error()
   [string "@PitBull4\UnitFrame.lua"]:66: func()
   [string "@PitBull4\Main.lua"]:1872:
      PitBull4\Main.lua:1866
   [string "=(tail call)"]: ?
   [string "@PitBull4\Main.lua"]:1512: OnProfileChanged()
   [string "@PitBull4\Main.lua"]:1597:
      PitBull4\Main.lua:1570
   [string "=[C]"]: ?
   [string "@!!!Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70:
      ...ce\AddOns\!!!Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65
   [string "@!!!Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:527: EnableAddon()
   [string "@!!!Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:630:
      ...ce\AddOns\!!!Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:615
Locals:
None
AddOns:
  Libs, v
  Swatter, v2.5.6773 (SwimmingSeadragon)
  AtlasBurningCrusade, vv1.50.02
  AtlasClassicWoW, vv1.50.02
  AtlasWrathoftheLichKing, vv1.51.02
  AtlasLootClassic, vv3.0.0-beta2
  AtlasLootClassicData, vv3.0.0-beta2
  AtlasLootClassicDungeonsAndRaids, vv3.0.0-beta2
  Auctionator, v2.5.5-1-g17bf777
  BagnonForever, v1.1.1
  BattleGroundEnemies, v9.2.0.11
  BattleInfo, v@project-version
  BaudAuction, v
  BeanCounter, v2.5.6767 (SwimmingSeadragon)
  BigFoot, v
  BigFootBar, v
  BigFootBot, v
  BigWigs, vv43-classic
  BigWigsNaxxramas, vv43-classic
  BigWigsOnyxia, vv43-classic
  BlizzMove, vv1.2.2
  BuffTimers, vv1.5.11
  ChannelFilter, v
  CharacterStatsTBC, v1.2.4
  ChatCopyPaste, v1.13
  ClassicCodex, vv0.4.9
  ClassicCodexdb, vv0.4.9
  ClassicCodexdbzhCN, vv0.4.9
  ClassicCodexloader, vv0.4.9
  ClassicCodexpatch, vv0.4.9
  ClassicSpellActivations, v
  Combuctor, v606
  DBMCore, v99722e9
  DBMSpellTimers, vr139
  DBMStatusBarTimers, v99722e9
  DBMVPYike, v20220320
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DruidBarClassic, v0.7.12
  Enchantrix, v2.5.6768 (SwimmingSeadragon)
  EnchantrixBarker, v2.5.6769 (SwimmingSeadragon)
  ExAutoEquip, v
  ExRT, v4650
  HandyNotes, vv1.6.6
  HandyNotesDungeonLocationsClassic, v1.05-bcc
  HandyNotesNPCsBurningCrusadeClassic, v1.08
  HandyNotesTravelGuide, vv1
  HandyNotesTravelGuideBCC, vv3.4
  ItemRack, v
  MailLogger, v1.4.8
  Mapster, v1.9.8
  MeetingHorn, v1.7.10
  Mendeleev, v3.0
  MRT, v4650
  NovaWorldBuffs, v2.30
  NugRunning, v9.2.2
  PitBull4, vv4.3.5-classic
  RaidLedger, vv1.9.5-v2.5.2
  RFA, v1.0.0
  sArena, v1.8
  SlideBar, v2.5.6771 (SwimmingSeadragon)
  Spy, v3.0.0
  Stubby, v2.5.6772 (SwimmingSeadragon)
  TalentEmu, v304r.220901-3
  tdInspect, v2.0.2
  TidyPlatesThreatPlates, v10.5.0
  TotemTimers, v3.0.0
  Wargame, v1.1.10
  WclPlayerScoreTBC, v2.1.52
  WclPlayerScoreTBCDB2, v
  WeakAuras, v4.1.2
  WeakAurasCompanion, v1.1.0
  BlizRuntimeLib_zhCN v3.4.0.30400 <none>
  (ck=7be)

**Comment by absgbnb1** [comment]
PitBull4_Aura: Unknown spell ID: 19478
PitBull4_Aura: Unknown spell ID: 19480
PitBull4_Aura: Unknown spell ID: 29203
PitBull4_Aura: Unknown spell ID: 8836
PitBull4_Aura: Unknown spell ID: 15108
PitBull4_Aura: Unknown spell ID: 25909
PitBull4_Aura: Unknown spell ID: 30029
PitBull4_Aura: Unknown spell ID: 2651
PitBull4_Aura: Unknown spell ID: 20580
PitBull4_Aura: Unknown spell ID: 20162
PitBull4_Aura: Unknown spell ID: 26635
PitBull4_Aura: Unknown spell ID: 18137
PitBull4_Aura: Unknown spell ID: 2652
PitBull4_Aura: Unknown spell ID: 13896
PitBull4_Aura: Unknown spell ID: 2651
PitBull4_Aura: Unknown spell ID: 2652
PitBull4_Aura: Unknown spell ID: 18137
PitBull4_Aura: Unknown spell ID: 30300
PitBull4_Aura: Unknown spell ID: 128
PitBull4_Aura: Unknown spell ID: 13896
PitBull4_Aura: Unknown spell ID: 29063
PitBull4_Aura: Unknown spell ID: 23099
PitBull4_Aura: Unknown spell ID: 19229
PitBull4_Aura: Unknown spell ID: 19410
PitBull4_Aura: Unknown spell ID: 10797
PitBull4_Aura: Unknown spell ID: 2878
PitBull4_Aura: Unknown spell ID: 9035
PitBull4_Aura: Unknown spell ID: 17390
PitBull4_Aura: Unknown spell ID: 44041
PitBull4_Aura: Unknown spell ID: 9035
PitBull4_Aura: Unknown spell ID: 10797
PitBull4_Aura: Unknown spell ID: 15269
PitBull4_Aura: Unknown spell ID: 704
PitBull4_Aura: Unknown spell ID: 18265
PitBull4_Aura: Unknown spell ID: 17862

**Comment by absgbnb1** [comment]
Date: 2022-09-04 03:03:29
ID: 1
Error occured in: Global
Count: 1
Message: LibDogTag-3.0.20210628: Error with code "[Classification] [Level:DifficultyColor] [(if (IsPlayer or (IsEnemy and not IsPet)) then Class):ClassColor] [DruidForm:Paren] [SmartRace]" (Base;Unit). ...agTexts\Libs\LibDogTag-Unit-3.0\Categories\Auras.lua line 42:
   attempt to perform arithmetic on local 'count' (a string value)
Debug:
   [string "@PitBull4_DogTagTexts\Libs\LibDogTag-3.0\LibDogTag-3.0.lua"]:304:
      ...ll4_DogTagTexts\Libs\LibDogTag-3.0\LibDogTag-3.0.lua:290
   [string "@PitBull4_DogTagTexts\Libs\LibDogTag-3.0\LibDogTag-3.0.lua"]:440: AddFontString()
   [string "@PitBull4_DogTagTexts\DogTagTexts.lua"]:216:
      ...nterface\AddOns\PitBull4_DogTagTexts\DogTagTexts.lua:203
   [string "=(tail call)"]: ?
   [string "@PitBull4\ModuleHandling\TextProviderModule.lua"]:121: UpdateFrame()
   [string "@PitBull4\ModuleHandling\Module.lua"]:314: Update()
   [string "@PitBull4\UnitFrame.lua"]:771: Update()
   [string "@PitBull4\ModuleHandling\Module.lua"]:512: EnableModuleAndSaveState()
   [string "@PitBull4\Main.lua"]:1422: LoadAndEnableModule()
   [string "@PitBull4\Options\Modules.lua"]:112:
      PitBull4\Options\Modules.lua:110
   [string "=[C]"]: ?
   [string "@!!!Libs\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:51:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49
   [string "@!!!Libs\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:836:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:657
   [string "=[C]"]: ?
   [string "@!!!Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:72:
      ...erface\AddOns\!!!Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:70
   [string "@!!!Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:306: Fire()
   [string "@!!!Libs\Ace3\AceGUI-3.0\widgets\AceGUIWidget-Button.lua"]:22:
      ...Libs\Ace3\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19
Locals:
None
AddOns:
  Libs, v
  Swatter, v2.5.6773 (SwimmingSeadragon)
  AtlasBurningCrusade, vv1.50.02
  AtlasClassicWoW, vv1.50.02
  AtlasWrathoftheLichKing, vv1.51.02
  AtlasLootClassic, vv3.0.0-beta2
  AtlasLootClassicData, vv3.0.0-beta2
  AtlasLootClassicDungeonsAndRaids, vv3.0.0-beta2
  Auctionator, v2.5.5-1-g17bf777
  AutoEquip, v
  BagnonForever, v1.1.1
  BattleGroundEnemies, v9.2.0.11
  BattleInfo, v@project-version
  BaudAuction, v
  BeanCounter, v2.5.6767 (SwimmingSeadragon)
  BFCastingBar, v
  BFCooldown, v
  BFGadgets, v
  BFGoldFrame, v
  BFQuest, v
  BFTooltip, v
  BigDebuffs, vv11.1
  BigFoot, v
  BigFootBar, v
  BigFootBot, v
  BigFootChat, v
  BigWigs, vv43-classic
  BigWigsNaxxramas, vv43-classic
  BigWigsOnyxia, vv43-classic
  BlizzMove, vv1.2.2
  BuffMaster, v
  BuffTimers, vv1.5.11
  ChannelFilter, v
  CharacterStatsTBC, v1.2.4
  ChatCopyPaste, v1.13
  ClassicCodex, vv0.4.9
  ClassicCodexdb, vv0.4.9
  ClassicCodexdbzhCN, vv0.4.9
  ClassicCodexloader, vv0.4.9
  ClassicCodexpatch, vv0.4.9
  ClassicSpellActivations, v
  CombatIndicator, v
  Combuctor, v606
  DBMCore, v99722e9
  DBMSpellTimers, vr139
  DBMStatusBarTimers, v99722e9
  DBMVPYike, v20220320
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DruidBarClassic, v0.7.12
  Enchantrix, v2.5.6768 (SwimmingSeadragon)
  EnchantrixBarker, v2.5.6769 (SwimmingSeadragon)
  ExAutoEquip, v
  ExRT, v4650
  HandyNotes, vv1.6.6
  HandyNotesDungeonLocationsClassic, v1.05-bcc
  HandyNotesNPCsBurningCrusadeClassic, v1.08
  HandyNotesTravelGuide, vv1
  HandyNotesTravelGuideBCC, vv3.4
  Informant, v2.5.6770 (SwimmingSeadragon)
  ItemInfo, v
  ItemRack, v
  MailLogger, v1.4.8
  MailMod, v
  Mapster, v1.9.8
  MeetingHorn, v1.7.10
  Mendeleev, v3.0
  MerInspect, v1.0.3
  MobHealth, v
  MRT, v4650
  MySlot, vv5.8.0-v2.5.2
  NovaWorldBuffs, v2.30
  NugRunning, v9.2.2
  Omen, v3.2.4
  PitBull4, vv4.3.5-classic
  PitBull4DogTagTexts, vv4.3.5-classic
  QuickCompare, v
  RaidAlerter, v5.3.1
  RaidLedger, vv1.9.5-v2.5.2
  RangeDisplay, vv4.9.8
  Recount, vv2.5.3c
  RepairHelper, v
  RFA, v1.0.0
  sArena, v1.8
  SellerHelper, v
  SlideBar, v2.5.6771 (SwimmingSeadragon)
  Spy, v3.0.0
  Stubby, v2.5.6772 (SwimmingSeadragon)
  TalentEmu, v304r.220901-3
  tdInspect, v2.0.2
  TheBurningTrade, v
  TidyPlatesThreatPlates, v10.5.0
  TotemTimers, v3.0.0
  TUnitFrame, v
  Wargame, v1.1.10
  WclPlayerScoreTBC, v2.1.52
  WclPlayerScoreTBCDB2, v
  WeakAuras, v4.1.2
  WeakAurasCompanion, v1.1.0
  WhisperPop, v3.1
  BlizRuntimeLib_zhCN v3.4.0.30400 <none>
  (ck=9df)

**Comment by nebularg** [comment]
1) Focus issue should be fixed
2) I still need to update the aura filters (but the print is off for now
3) I saw LibDogTags got a wrath release, so the next PB4 will pull that

Let me know if you get any more errors, thanks!

**Comment by absgbnb1** [comment]
Thanks!
