### ISSUE TITLE
Absolute health showing as 100/100 on all other players/mobs.

### ISSUE THREAD

**Issue by phenx24** [nebularg/PitBull4#4]
Hey, on the classic version absolute health showed as 100/100 on all other players/mobs. I've tried with only pitbull enabled and ran into same issue. Thanks

**Comment by nebularg** [comment]
You need [Real Mob Health](https://www.wowinterface.com/downloads/info24924-RealMobHealth.html) to see the actual values, this info isn't available in Classic.
