### ISSUE TITLE
Update for DF.

### ISSUE THREAD

**Issue by Dools1337** [nebularg/PitBull4#45]
Not sure that's the right place to ask you this... If not please forgive me. Are you going to update your addon for DF?

Just wondering because you don't have any alpha/beta build yet.

Regards,

**Comment by nebularg** [comment]
What's broken?

**Comment by Dools1337** [comment]
At least on beta right now. If you enable Hide Blizzard Frames
You get this 

![image](https://user-images.githubusercontent.com/55139207/197500860-aade5da8-4f21-429c-b26b-15908846c3cd.png)

And no more regular frames.

I was just wondering if you were planning on updating your awesome addon to 10.0 or I should look for a replacement. (like SUF or something)

Regards,

**Comment by nebularg** [comment]
Yes, I'm still playing and hadn't encountered any errors yet
