### ISSUE TITLE
3D Portrait won't fade properly on Character 

### ISSUE THREAD

**Issue by Uggers** [nebularg/PitBull4#48]
This is a duplicate to the issue on curseforge, I just wasn't sure the proper reporting page, apologies if this isn't it;

I have an odd error where my character portrait won't vanish on the fade properly as per the 2 screenshots, what it looks like when targeting normally, but for some reason on the player frame the character won't fade out.
 
This happens on Pirate day as well for some odd reason, I think blizzard forces a hate on your in your portrait but not actually on your character model in game, but I usually just ignore it for the day its doing it

 
Normal
![image](https://user-images.githubusercontent.com/6855065/199229929-93b54cbc-4a46-4bee-a910-4ca0f1fb85eb.png)

When fade should apply
![image](https://user-images.githubusercontent.com/6855065/199229951-98d35d8c-3977-4bd5-bcd3-145555d6fe6c.png)

**Comment by Uggers** [comment]
sorry just to add, its the portrait under indicator that i'm using here

**Comment by nebularg** [comment]
Fixed in https://github.com/nebularg/PitBull4/commit/8af27c79af9163e819227fd8328311a973fa582b

**Comment by loeppenberg** [comment]
this might be broken again, as described here
https://www.curseforge.com/wow/addons/pitbull-unit-frames-4-0/issues/1409
