### ISSUE TITLE
RangeFader broken

### ISSUE THREAD

**Issue by kreptafire** [nebularg/PitBull4#68]
WoW API change in 11.0.2

https://warcraft.wiki.gg/wiki/API_C_Spell.IsSpellInRange

In RangeFader.lua, change all instances of IsSpellInRange to C_Spell.IsSpellInRange, to fix it.

**Comment by nebularg** [comment]
https://github.com/nebularg/PitBull4/blob/master/Modules/RangeFader/RangeFader.lua#L7

you're going to have to be more specific

**Comment by nebularg** [comment]
Thanks!

**Comment by kreptafire** [comment]
No problem!
