### ISSUE TITLE
Buffs not showing up anymore

### ISSUE THREAD

**Issue by Derfla92** [nebularg/PitBull4#73]
8x PitBull4/modules_Cata.xml:9 Couldn't open PitBull4/Modules/Aura/load_Cata.xml

**Comment by Derfla92** [comment]
After a bit of searching in the source code ive sort of come to the conclusion that a file is missing.

**Comment by nebularg** [comment]
https://github.com/nebularg/PitBull4/commit/5e20055dbae18b3bd6bb8c93b40018f1c845b537
