### ISSUE TITLE
something wrong with cast bar

### ISSUE THREAD

**Issue by znuaile** [nebularg/PitBull4#8]
In the latest classic version ,I create a cast bar separately for fixing name bar and mana bar size  ,and I set cast bar auto hide .I am a rogue.After using bandage,the cast bar can not auto-hide normally,  while casting Other spells or using  items with cast bar , it (the cast bar) can hide normally.  

![cast](https://user-images.githubusercontent.com/45118972/66486614-903b7b00-eadd-11e9-838d-6f34bb940c32.PNG)

**Comment by nebularg** [comment]
Should be fixed now
